export enum SettingsCallbackType {
  SET_AMOUNT = "SET_AMOUNT",
  SET_INTERVAL = "SET_INTERVAL",
  SET_SLIPPAGE = "SET_SLIPPAGE",
  SET_PRIORITY_FEE = "SET_PRIORITY_FEE",
  SET_BUMPS_LIMIT = "SET_BUMPS_LIMIT",
}
