export enum PricingAction {
  BUY_SERVICE_PASS = "BUY_SERVICE_PASS",
  BUY_TOKEN_PASS = "BUY_TOKEN_PASS",
  USE_TOKEN_PASS = "USE_TOKEN_PASS",
}

export const BUY_PLAN_VALIDATOR_TIP_IN_SOL = 0.0001;
export const BUY_PLAN_PRIORITY_FEE_IN_SOL = 0.001;

export const IS_PRICE_INCLUSIVE = false;
